### PR TITLE
Add Brunch support 

### PR DESCRIPTION
**Pull request by Taranys**
Add support for [Brunch](http://brunch.io)

Same way as Gulp or Grunt

### CODE REVIEW

**Comment by mriehema** [comment]
+1

**Comment by derekjwilliams** [comment]
It would be awesome to get these changes merged back to master

**Comment by commonquail** [comment]
I'm interested in this addition, however, although [it looks like](https://github.com/brunch/brunch/blob/d9a8226a4074ca2922ce8819c832114b2ee5964b/docs/upgrading.md)  `config.coffee` should still work [the recommended name](https://github.com/brunch/brunch/blob/2d727285688a7bf4acc2140f154ba96cf2d8b04d/docs/config.md)  is `brunch-config`. It is unclear whether the JavaScript or CoffeeScript version is preferred: the core documentation indicates JavaScript but [the guide says the opposite](https://github.com/brunch/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md#configuration-files).

The integration should offer the least friction so it should default to the most likely file name. [GitHub's lacklustre search indicates a small preference for `brunch-config.coffee`](https://github.com/search?p=1&q=brunch-config&ref=searchresults&type=Code&utf8=%E2%9C%93). Fallback JS support could also be an idea.

**Comment by nikeee** [comment]
I really miss this plugin. Any updates on this PR?

**Comment by mriehema** [comment]
Instead of adding another build tool, I recommend to use npm scrips instead. We should close this PR.

**Comment by nikeee** [comment]
You're right. I'll try this instead.

**Pull request closed without merging**
