### PR TITLE
Change Travis Configuration

### PR DESCRIPTION
**Pull request by mriehema**
- add linux
- switch to jdk8
- change language

### CODE REVIEW

**Comment by eirslett** [comment]
Is it possible to use Java 7?

**Comment by mriehema** [comment]
Sure, if you want, even both JDKs.

**Comment by eirslett** [comment]
It's enough with only Java 7, then the build will be faster as well.

**Comment by mriehema** [comment]
Travis changed the default JDK for OSX to Java 8. Its not possible to change it. See https://github.com/travis-ci/travis-ci/issues/6716 All I can do, is switch back to an old OSX version 10.9. I would prefer using JDK8 with a new OSX.

**Comment by mriehema** [comment]
@eirslett Something missing or wrong for a merge?

**Comment by eirslett** [comment]
Oh sorry, I thought this was already merged. Thanks! Will merge it now.

**Pull request merged**
