### PR TITLE
Fix Regex error in NodeTaskExecutor #192

### PR DESCRIPTION
**Pull request by kwa**
Attempt to find user name and password in proxy argument string and mask it.
Passes the following likely and some very unlikely scenarios:
```
public static class Testing {
    public static void main(String[] args) {
        assert NodeTaskExecutor.maskPassword(null) == null;
        assert "".equals(NodeTaskExecutor.maskPassword(""));
        assert " ".equals(NodeTaskExecutor.maskPassword(" "));
        assert "proxy=//abc:def@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=//abc:def@example.com:8080"));
        assert "proxy=http://abc:***@1.2.3.4:8080".equals(NodeTaskExecutor.maskPassword("proxy=http://abc:def@1.2.3.4:8080"));
        assert "proxy=http://abc:***@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=http://abc:de:f@example.com:8080"));
        assert "proxy=http:////:***@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=http:////:::@example.com:8080"));
        assert "proxy=http://///@/:***@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=http://///@/::://:@:@example.com:8080"));
        assert "proxy=http:// ///@/:***@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=http:// ///@/::://:@ :@example.com:8080"));
        assert "proxy=https:// ///@/:***@example.com:8080".equals(NodeTaskExecutor.maskPassword("proxy=https:// ///@/::://:@ :@example.com:8080"));
    }
}
```

### CODE REVIEW

**Comment by eirslett** [comment]
I fixed the failed build now. Could you please rebase this on top of master, and then see if it builds?

**Comment by kwa** [comment]
@eirslett I have updated this branch. I tried to rebase but need to merge a conflict between "Proxy config now includes (and displays) id", the getId() in ProxyConfig constructor caused the conflict. I see now that the rebase did not do what I expected. Not sure if that is why AppVeyor is having problems...

Should I redo and perform a merge instead?... It should yield a fast-forward... I will test locally.

**Comment by kwa** [comment]
I did a merge instead and that worked better. Still unfortunate that the rebase did not work.. wondering if rebase and merge uses different merge strategies as I did not get any merge conflicts when using a regular merge.
Seems that the build has passed, so everthing OK or not @eirslett ?

**Comment by eirslett** [comment]
Everything looks ok now! Thanks!

**Pull request merged**
