### PR TITLE
Some fixes of the webpack support.

### PR DESCRIPTION
**Pull request by stanislavpavlicek**

### CODE REVIEW

**Comment by eirslett** [comment]
Sorry for the late reply!
Why tweak the --no-color flag? Doesn't it exist in webpack?

**Comment by stanislavpavlicek** [comment]
Yes, the webpack CLI doesn't have a --no-color flag.

**Comment by eirslett** [comment]
Ok. Thanks for the PR!

**Comment by eirslett** [comment]
Oops, looks like it doesn't merge... would you mind rebasing it. please?

**Comment by stanislavpavlicek** [comment]
done

**Comment by eirslett** [comment]
Thanks!

**Pull request merged**
