### PR TITLE
Enables colors for all runners by default.

### PR DESCRIPTION
**Pull request by MadaraUchiha**
After reading #180 and #122, I've seen that you're waiting for a PR.

People with build systems that bork on colors can disable the specific platform's colors via the arguments passed.

### CODE REVIEW

**Comment by eirslett** [comment]
Thanks! Let's remove the parameter from the abstract class as well?

**Comment by MadaraUchiha** [comment]
I haven't found any further instance of "color" in the entire project. I did miss the README though, I'll be pushing an update to that soon.

**Comment by eirslett** [comment]
It's called "additionalArguments" in NodeTaskExecutor. Is it used somewhere else?

**Comment by MadaraUchiha** [comment]
Yes, It's still used by DefaultBowerRunner's constructor (with `buildArguments(proxyConfig)`) and with DefaultWebPack runner, with an empty list (I'll just go ahead and remove that). 

The proxyConfig are passed from BowerMojo in line 41, where it gets generated with
```java
ProxyConfig proxyConfig = MojoUtils.getProxyConfig(session, decrypter);
```

I'm not really into Maven plugin development, so I'm not entirely sure what this method does. I'm fairly sure it's not related to output coloring. (I'm also not sure if this proxy configuration needs to use the additional arguments parameter, I don't know what's being passed there).

**Comment by eirslett** [comment]
Ok, let's leave it for now... I'm not quite sure if the proxy stuff uses it or not.
Thanks for the PR!

**Pull request merged**
