### PR TITLE
Fix regression when extracting tar archive to a path containig a symlink

### PR DESCRIPTION
**Pull request by arminha**
This was originally fixed in pull request #816, but got lost when pull request #843 got merged.

This pull request fixes the issue again and adds unit tests to test the relevant code in the DefaultArchiveExtractor.

### CODE REVIEW

**Comment by martin-g** [comment]
+1 for the fix and a release this year! Thanks :-)

**Comment by eirslett** [comment]
Ok, let's do this!

**Comment by eirslett** [comment]
There we go, 1.9.0 is released, merry christmas! 🎅 ❄️ 🎄

**Comment by martin-g** [comment]
Merry Christmas! :mrs_claus: 
Thank you! :dango:

**Pull request merged**
