### PR TITLE
Adding support for the “ember” command line, from ember-cli

### PR DESCRIPTION
**Pull request by joachimhs**
In order to be able to support ember-cli builds with this plugin via Maven, I have added an EmberMojo class, and and "ember" build goal. 

I suppose there might also be an "InstallEmberCli" mojo that executed npm install ember-cli, however.

### CODE REVIEW

**Comment by chrisvdp** [comment]
Can it run the ember cli tests via `ember test`?

**Comment by joachimhs** [comment]
Running ember test is currently not built in, but this is definitely one area where we are also interested in extending the plugin into. Making the build fail when test fail is an important step towards getting Ember streamlined into the CI process.

**Comment by eirslett** [comment]
Thanks! Looks good to me.
If "ember test" returns exit code 1 (or something other than 0) when it fails, the build should fail too.

**Comment by chrisvdp** [comment]
@joachimhs how does it work?

**Pull request merged**
