### PR TITLE
adding s390x support

### PR DESCRIPTION
**Pull request by kadamvandita**
**Summary**
Added support for s390x.

There was no support for s390x.Added a case statement  for s390x support in Platform.java file

**Tests and Documentation**

### CODE REVIEW

**Comment by eirslett** [comment]
Will it also generate the correct node.js download file name?

**Comment by kadamvandita** [comment]
Yes..correct file will be genarated

**Comment by eirslett** [comment]
ok, thanks!

**Comment by kadamvandita** [comment]
Hi,

How will the jar be created for frontend maven plugin for s390x?

**Comment by eirslett** [comment]
I have no idea. I don't have access to a s390x machine. To be honest I've never heard about s390x before now...

**Comment by kadamvandita** [comment]
Hi,

In which version can I expect the jar for s390x?

**Comment by eirslett** [comment]
Since it's merged, it will end up in the next release.

**Comment by kamathd** [comment]
@eirslett do you know the next release date ?

**Comment by kadamvandita** [comment]
The jar for 1.5 maven front end plugin is yet not there in maven central repo. when will the jar be available in the maven central repo?

**Comment by eirslett** [comment]
Sorry, the release process for OSS Sonatype is a major PITA, so there was some trouble along the way. It should be released now.

**Comment by eirslett** [comment]
rage

**Comment by eirslett** [comment]
I tried again now. Should be out in a couple of hours...

**Comment by kamathd** [comment]
Sure. thanks.

**Comment by eirslett** [comment]
There it is! https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/1.5/

**Comment by kadamvandita** [comment]
Thanks .

But when I tried adding <plugin.frontned.version>1.5</plugin.frontned.version> in pom.xml, it still throws the warning The POM for com.github.eirslett:frontend-maven-plugin:jar:1.5 is missing, no dependency information available. Is there somewhere else the jar needs to be made available?

**Comment by eirslett** [comment]
you could try deleting it from your local .m2 cache

**Pull request merged**
