### PR TITLE
Added support for jspm.

### PR DESCRIPTION
**Pull request by yazybones**
Added support for using jspm (http://jspm.io/) for package management.

### CODE REVIEW

**Comment by theonlyguills** [comment]
I'd like this feature merged too! Thanks!

**Comment by m0ru** [comment]
+1! :3

**Comment by FagnerMartinsBrack** [comment]
What jspm does that npm can't?

**Comment by m0ru** [comment]
What I've seen so far of it: access to the npm- and bower-registries (as well as it's own), and it comes with a nice es6-module-loading- and transpiling-enviroment (it's backwards compatible to CommonJS/AMD as well). Also, it tree-shakes and minifies really well ([here's](https://github.com/m0ru/tooling-for-angular-1.4#unminified-sizes) a small comparison i put together over the weekend). Anyway, that's what I found out during my last week of playing around with it. <http://jspm.io/> is probably a better source to get reliable information from ^^

I'm currently adding it to our angular project, which needs to deploy to a tomcat-server. All of the server-side projects use maven to build and running `jspm ìnstall` as exec-maven is cumbersome, especially compared to frontend-maven.

**Comment by FagnerMartinsBrack** [comment]
I have a project that also uses Java in the back-end, with [npm](https://github.com/FagnerMartinsBrack/WebStories/blob/6f8de39897bc75d6b469ebd81661d117402f6c7a/package.json), and a hybrid of [angularJS](https://github.com/FagnerMartinsBrack/WebStories/tree/6f8de39897bc75d6b469ebd81661d117402f6c7a/src/main/webapp/js/custom/angular) and [vanillaJS](https://github.com/FagnerMartinsBrack/WebStories/blob/6f8de39897bc75d6b469ebd81661d117402f6c7a/src/main/webapp/jsp/pages/index.js) in the front-end.

In my experience I haven't seen a strong use case to use anything else than npm and bower.

Anyway, it's up to the author to decide if this is worth supporting, only the existence of this PR already helps a lot for anyone interested in using it in a fork.

**Comment by fkleedorfer** [comment]
+1 
@eirslett Any chance to get this merged? 
We're looking into building a workaround with maven-exec-plugin, and it's not exactly resulting in easily reproducible builds.

**Comment by theonlyguills** [comment]
In the meantime you can just clone @yazybones 's repo and install the merged version in your local maven repo. 

I've been using that version at work for a couple weeks.

**Comment by eirslett** [comment]
Looks like there is a merge conflict or something... I'll merge it when that's fixed.
What I suggest that you do instead of the maven-exec-plugin is to use the npm mojo with arguments like `<arguments>run-script node_modules/bin/jspm.js myargs</arguments>` (pseudocode, I'm not 100 % sure how it should be set up)

**Comment by fkleedorfer** [comment]
@theonlyguills @eirslett Thanks! 
We want to avoid any workaround because they tend to petrify. I guess we can wait for the merge, now we know it's coming.

**Comment by eirslett** [comment]
@yazybones could you please have a little look at the merge conflict?

**Comment by yazybones** [comment]
@eirslett updated, should be good to merge now.

**Comment by eirslett** [comment]
Thanks a lot!

**Pull request merged**
