### PR TITLE
Add proxy environment variables for npm postinstalls

### PR DESCRIPTION
**Pull request by Cavva79**
**Summary**

Found that for postinstall script, such openlayers 4 has, in a proxy network, this plugin is not passing right the proxy to node.js running the script.

**Tests and Documentation**

This fixes issue #657.
I tested and it seems to work with openlayers 4.6.4

### CODE REVIEW

**Comment by Cavva79** [comment]
@eirslett I think this pull request may fix also issue #700, do you have any plans to merge?

**Comment by xmj** [comment]
Any chance of getting this merged?

**Comment by MichaelCkr** [comment]
@eirslett We would also and still appreciate the merge of this pull request.

**Comment by ironijunior** [comment]
@Cavva79 or @eirslett do you guys have any news on this PR? 😃

**Comment by josehenriqueventura** [comment]
Hey @Cavva79/@eirslett ,
Any idea about this PR, please?

**Comment by eirslett** [comment]
Sorry, looks like I botched the merge commit. There is a conflict against the master branch, could somebody please just pick up the code from this PR and make a new PR that works against the latest master? I'll promise to merge it!

**Comment by josehenriqueventura** [comment]
@eirslett there you go https://github.com/eirslett/frontend-maven-plugin/pull/1095

**Comment by josehenriqueventura** [comment]
@Cavva79 do you want to fix this PR? I should have asked it first.

**Comment by Cavva79** [comment]
@josehenriqueventura go ahead. I am unable to fix it now ☺️

**Pull request merged**
