### PR TITLE
Implement getAbsoluteTaskLocation to work similar to the standard NPM

### PR DESCRIPTION
**Pull request by Antibrumm**
task locator: Traverse up the parent directory until we find the
taskLocation. (Does not go global finally, if not found)

This supports multi module projects to consolidate node_modules on the
parent module:

parent -> frontend plugin install
module -> frontend plugin grunt / karma etc.

### CODE REVIEW

**Comment by Antibrumm** [comment]
Any interest in this?

**Comment by eirslett** [comment]
Isn't this easier to solve by building an absolute url, based on Maven's variables like ${project.basedir}?

**Comment by Antibrumm** [comment]
Initially I have tried to use a mix of install and working directories and couldn't get it running.  
NPM is going up the directory structure to resolve dependencies and task scripts, but for the initial call to "grunt" or "karma" this resolution is not done by the task runners. Is there a way to tell the plugin where the task scripts are located?

**Comment by Antibrumm** [comment]
Closing this one as I think I found a better way

**Pull request closed without merging**
