### PR TITLE
add condition to arm arch with non v7 version.

### PR DESCRIPTION
**Pull request by jackiehxm0228**
Such condition exist in most recent Raspberry Pi OS version 5.10.63-v8+

**Summary**

**Tests and Documentation**

### CODE REVIEW

**Comment by jackiehxm0228** [comment]
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux
pi@raspberrypi:~ $ java -jar test.jar
arch: arm
version: 5.10.63-v8+

**Comment by jackiehxm0228** [comment]
Any updates on this pull request?

**Comment by jackiehxm0228** [comment]
If you don't like what I have changed, please remove linux x86 version cause it does not exist anymore.
Nodejs download directory: https://nodejs.org/dist/v16.14.2/
Maven build log: [INFO] Downloading https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x86.tar.gz to /var/lib/jenkins/.m2/repository/com/github/eirslett/node/16.14.2/node-16.14.2-linux-x86.tar.gz

**Comment by eirslett** [comment]
Oh sorry, I completely missed this! Looks good to me, I guess.

**Comment by jackiehxm0228** [comment]
Thank you Sir! Have a great day!

**Pull request merged**
