### PR TITLE
Install npm properly so that it can be used in the scripts section of package.json

### PR DESCRIPTION
**Pull request by klieber**
If you have a package.json with a scripts section that uses the npm command like this:

```json
{
  "name": "myproject",
  "version": "0.0.1",
  "dependencies": {
    "grunt": "~0.4.1",
    "grunt-cli": "~0.1.9"
  },
  "scripts": {
    "prebuild": "npm install",
    "build": "grunt"    
  }
}
```

and a plugin configuration like this:

```xml
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <version>@project.version@</version>
  <executions>
    <execution>
      <goals>
        <goal>install-node-and-npm</goal>
        <goal>npm</goal>
      </goals>
      <configuration>
        <nodeVersion>v0.12.2</nodeVersion>
        <npmVersion>2.7.6</npmVersion>
        <arguments>run build</arguments>
      </configuration>
    </execution>
  </executions>
</plugin>
```

Then the frontend-maven-plugin should run `npm run build` which will then run `npm install` and then `grunt`. However, instead you will get the following error:

```
[INFO] --- frontend-maven-plugin:0.0.24:npm (default) @ myproject ---
[INFO] Running 'npm run build --color=false' in C:\myproject
[INFO]
[INFO] > myproject@ prebuild C:\myproject
[INFO] > npm install
[INFO]
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'C:\myproject\node\npm\bin\node_modules\npm\bin\npm-cli.js'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
[ERROR]
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "C:\\myproject\\node\\node.exe" "C:\\myproject\\node\\npm\\bin\\npm-cli.js" "run" "build" "--color=false"
[ERROR] npm ERR! node v0.12.2
[ERROR] npm ERR! npm  v2.8.4
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! myproject@ prebuild: `npm install`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the myproject@ prebuild script 'npm install'.
[ERROR] npm ERR! This is most likely a problem with the myproject package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     npm install
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls myproject
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\myproject\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

This pull request changes the npm install directory to `/node/node_modules/npm` instead of `/node/npm` so that is matches the location that it would be installed if you installed node manually.  This change also copies `npm` and `npm.cmd` from the `/node/node_modules/npm/bin/` directory into the `/node` directory next to the `node` executable, which is again that same as the manual installer would do.  After these changes the plugin works as expected.

### CODE REVIEW

**Comment by eirslett** [comment]
Looks good to me! Just a few points:
1) Is this change backwards-compatibly if somebody runs a build with the "node" folder from an older version of the plugin, and then upgrades to a version with this change, without nuking the "node" folder? Is that what the oldNpmDirectory stuff is about?
2) Can we set it up to run a simple Gulpfile with a simple task `console.log("gulp runs as expected")` instead of Grunt, since Grunt is already run once in the integration test?

**Comment by klieber** [comment]
Yes, it is backwards compatible and that is what the `oldNpmDirectory` stuff is about.  I will look into running the gulp task.  Thanks!

**Comment by klieber** [comment]
@eirslett I've updated this to run the gulp task.  I also added a simple verify script to the integration test just to verify that things run properly.

**Comment by eirslett** [comment]
Thanks a lot! The verify script is great too! Solves a problem that, for some reason, hasn't been addressed yet.

**Pull request merged**
