### PR TITLE
add support for Alpine Linux using experimental nodejs download url

### PR DESCRIPTION
**Pull request by tnguyen1**
**Summary**

This pull request is an attempt to support _frontend-maven-plugin_ on **Alpine Linux**. The issue has been reported several times here and there: https://github.com/eirslett/frontend-maven-plugin/issues/633, https://github.com/eirslett/frontend-maven-plugin/issues/636, https://github.com/eirslett/frontend-maven-plugin/issues/287

The proposed solution is to detect when we are running under Alpine Linux (_musl libc_) using the `ldd` command. In such case, we should download from https://unofficial-builds.nodejs.org/download/release/ instead. Although experimental, these builds are stable enough for Alpine Linux in most cases.

This prevents from forcing _glibc_ into Alpine Linux, hence avoiding some annoying Warning messages.

**Caveats**

Currently the following integration test fails, but it's the same behaviour on *master* branch.
```
[ERROR] The following builds failed:
[ERROR] *  yarn-integration/pom.xml
[...]
Running post-build script: /some/path/to/frontend-maven-plugin/frontend-maven-plugin/target/it/yarn-integration/verify.groovy
java.lang.AssertionError: incorrect local repository location. Expression: buildLog.replace(java.io.File.separatorChar, (char) /).matches((?s).+Unpacking .+\Q/local-repo/com/github/eirslett/yarn/[1-9\.]*/yarn-[1-9\.]*.tar.gz\E into .+/target/node/yarn.+)
```

### CODE REVIEW

**Comment by digable1** [comment]
Can somebody review this please - after almost 5 months?  This is a much-desired capability that we have also just run into dur to the mixed linux distros we have that leverage _frontend-maven-plugin_

If the same test errors indeed happen in master as well as this PR, can that be a separate conversation that does not impede the review of this PR?

**Comment by leungbk** [comment]
I'm on NixOS and am encountering the same issue. It would be great if this could be reviewed.

**Comment by imacks** [comment]
hi i hit this issue today trying to build keycloak 10.0.1 on alpine 3.11. `node` downloaded cannot run on alpine bcos its for glibc. i had to hack the cache mechanism for it to build:

```
apk add nodejs ; \
alpine_nodever=$(node --version) ; \
alpine_nodever_num=$(echo "$alpine_nodever" | tail -c +2) ; \
kc_nodever=$(cat themes/pom.xml | grep nodeVersion | cut -d'<' -f2 | cut -d'>' -f2) ; \
sed -i "s/<nodeVersion>${kc_nodever}<\/nodeVersion>/<nodeVersion>${alpine_nodever}<\/nodeVersion>/g" themes/pom.xml ; \
mkdir -p "/tmp/node-${alpine_nodever}-linux-x64/bin" ; \
cp $(which node) "/tmp/node-${alpine_nodever}-linux-x64/bin/" ; \
tar cz -f "node-${alpine_nodever_num}-linux-x64.tar.gz" -C /tmp "node-${alpine_nodever}-linux-x64/bin/node" ; \
rm -rf "/tmp/node-${alpine_nodever}-linux-x64" ; \
mkdir -p "/root/.m2/repository/com/github/eirslett/node/${alpine_nodever_num}" ; \
mv "node-${alpine_nodever_num}-linux-x64.tar.gz" "/root/.m2/repository/com/github/eirslett/node/${alpine_nodever_num}/" ; \
```

After that `$M2_HOME/bin/mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean install` works.

**Comment by adriancole** [comment]
this would be handy for zipkin also who are trying to work in alpine

**Comment by adriancole** [comment]
I would suggest that if we can control the classifier, it could be simpler.

For example, you can already override the base URL like this:

```xml
          <nodeDownloadRoot>https://unofficial-builds.nodejs.org/download/release/</nodeDownloadRoot>
```

The main thing missing is to override the classifier, which is a small part of this change.

Ex to change this
```
https://unofficial-builds.nodejs.org/download/release/v12.18.4/node-v12.18.4-linux-x64.tar.gz
```

To this:
```
https://unofficial-builds.nodejs.org/download/release/v12.18.4/node-v12.18.4-linux-x64-musl.tar.gz
```

Note there are a few classifiers as it is:
```
node-v12.18.4-linux-armv6l.tar.gz                  15-Sep-2020 23:42            21402256
node-v12.18.4-linux-x64-musl.tar.gz                15-Sep-2020 23:18            23691939
node-v12.18.4-linux-x64-usdt.tar.gz                15-Sep-2020 23:56            23013495
```

If there was a way to override `Platform.getNodeClassifier()` per property, we could fix his with environment variables instead of trying to detect. Would that be easier to merge @eirslett? or should we consider continuing this approach?

**Comment by eirslett** [comment]
I guess this PR is the simplest way to implement. I'm not super happy about the complexity, but it's a feature that's requestad a lot. Looks like the build fails, though, I'm not sure why.

**Comment by adriancole** [comment]
Took a different stab here cc @eirslett @anuraaga https://github.com/eirslett/frontend-maven-plugin/pull/934

**Comment by eirslett** [comment]
Closed via #934 .

**Pull request closed without merging**
