### PR TITLE
Fix execution of Yarn 1.X & switch Travis to use OpenJDK 8

### PR DESCRIPTION
**Pull request by mtraynham**
**Summary**
#647

**Tests and Documentation**
Added a 1.X yarn test suite.  Didn't see a 1.6 section in the CHANGELOG, I can add if needed.

### CODE REVIEW

**Comment by eirslett** [comment]
Thanks!

**Comment by betalb** [comment]
If I'm not mistaken Oracle JDK 7 is no longer supported by travis CI
https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

**Comment by eirslett** [comment]
I see. There's no reason to build on java 7 anyways, let's just use openjdk8. @mtraynham could you please update the PR and update travis.yml as well?

**Comment by mtraynham** [comment]
`openjdk8` seems to be working now, but I think the MacOS build might be hanging for a while.  I'm not sure how long it took the other to eventually run.

**Comment by eirslett** [comment]
Green build. LGTM!

**Pull request merged**
