### PR TITLE
Fixes #41 #343 rewrites ProcessExecutor using commons-exec

### LINKED ISSUE #41: Node keeps running when killing maven
When running a Grunt watch task and hitting "Ctrl-C" to stop the process. Node.exe keeps running in the background.

I haven't found a way to kill node.exe other than going manually in the task manager...

We are using a watch task to compile sass files in the background.

### PR DESCRIPTION
**Pull request by tjuerge**
By using `commons-exec` instead of  plain `ProcessBuilder` we can support killing the Node process if the Maven build is stopped (via `ShutdownHookProcessDestroyer`). An optional timeout (which leverages `ExecuteWatchdog`) can be specified (not exposed to the task runners yet).

With `commons-exec` we get quote handling and variable substitution in arguments for free (via `CommandLine.addArgument()`).

A workaround for #343 is implemented as well.

### CODE REVIEW

**Comment by eirslett** [comment]
Looks like the build failed though...

**Comment by tjuerge** [comment]
It seems that the quote handling of arguments (which ``commons-exec`` enables by default) is the culprit for the build failure on unix. Disabling quote-handling fixes the build :)

**Comment by mriehema** [comment]
@tjuerge Could you resolve the conflicts for this pull request? Otherwise I would create a different pull request just for #343.

**Comment by mriehema** [comment]
Please close this PR, see #561 instead.

**Pull request closed without merging**
