### PR TITLE
Adding an installDirectory parameter

### PR DESCRIPTION
**Pull request by klieber**
This will allow you to specify a different directory to use for installing node and npm other than the working directory.

### CODE REVIEW

**Comment by klieber** [comment]
@eirslett any comments on this pull request?  This feature was originally requested in 2013 (see issue #18) and continues to have more and more people requesting it.

**Comment by sarumont** [comment]
+1 - downloading node every time you build is not optimal

**Comment by MattSchlobohm** [comment]
+1

**Comment by eirslett** [comment]
Hey! Thanks a lot for the pull request! I'll merge it soon. I just have to play with it a bit first, run the integration tests and so on. It would be nice with a little documentation to go with the PR! Have you tried whether the helper scripts in this project work with this change, or found a good solution on how to adjust them? They assume that node is installed in the default location.

**Comment by eirslett** [comment]
I tried this change now, looks good to me! Thanks for the contribution! :-)

**Comment by mriehema** [comment]
Could you please update the documentation. No one knows about this option and how to set it. ;)

**Comment by msieurtoph** [comment]
+1. No one knows ;)

**Comment by oscaritoro** [comment]
This is working for me for the node directory on my multi module project (get only one node folder at root), but the node_modules still gets rebuilt on each module. Is there no way to make sure that both node and node_modules go on the root folder? Here's how my root pom.xml looks:
```
                <plugin>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>0.0.26</version>
                    <configuration>
                        <installDirectory>${session.executionRootDirectory}</installDirectory>
                        </configuration>    
                    <executions>
                        <execution>
                            <id>install node and npm</id>
                            <goals>
                                <goal>install-node-and-npm</goal>
                            </goals>
                            <configuration>
                                <nodeVersion>v0.10.40</nodeVersion>
                                <npmVersion>1.4.28</npmVersion>
                            </configuration>
                        </execution>
                        <execution>
                            <id>npm install</id>
                            <goals>
                                <goal>npm</goal>
                            </goals>
                            <configuration>
                                <arguments>install</arguments>
                            </configuration>
                        </execution>
                        <execution>
                            <id>grunt build</id>
                            <goals>
                                <goal>grunt</goal>
                            </goals>
                            <configuration>
                                <arguments>build</arguments>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```

**Comment by PloughingAByteField** [comment]
I have similar issues with installDirectory and a multi-module project.
To get it to work I had to patch GruntRunner, GlupRunner and KarmaRunner due to the hardcoded TASK_LOCATION
I changed super(config, TASK_LOCATION, .....
to 
super(config, config.getInstallDirectory() + "/" + TASK_LOCATION, ......
adding getInstallDirectory() to NodeExecutorConfig
  @Override
  public File getInstallDirectory() {
    return installConfig.getInstallDirectory();
  }

it is not perfect but that hardcoded location does need looking at

**Comment by roger2hk** [comment]
I wonder why there is a `"/node"` after `workingDirectory` variable. It is not a good idea for Windows platform as the default Windows installation folder is `C:\Program Files\nodejs`.

**Comment by mriehema** [comment]
@roger2hk: Yes, it is a good idea. I have different workspaces with different node versions. So I don't want Maven to edit/break my node installation outside the workspace via this plugin. If you want to use your `C:\Program Files\nodejs`, just add `<installDirectory>`.

@oscaritoro: Your multimodule problem is not related to this plugin. It's default `npm `behaviour. Every `package.json` gets its `node_modules` folder.

**Comment by roger2hk** [comment]
@mriehema I tried to add `<installDirectory>` but the plug-in looks for `C:\Program Files\nodejs\node\node.exe` instead of `C:\Program Files\nodejs\node.exe`. This does not match the default Windows Node.js installation folder.

**Comment by eirslett** [comment]
Using C:\Program Files\... for installDirectory is pretty much a disaster for portability. What happens when the next developer, who's using OS X, tries to run mvn clean install? ;-)

A much better way to use the system-provided node.js binary is to do this: https://addyosmani.com/blog/making-maven-grunt/

**Comment by roger2hk** [comment]
@eirslett Thanks for your advice. That's a nice workaround.

**Pull request merged**
