### PR TITLE
Update Changelog for next 1.4 release

### PR DESCRIPTION
**Pull request by mriehema**
**Summary**

Changelog includes all merged pull requests. Maybe it's time for a new release. ;)

### CODE REVIEW

**Comment by wkillerud** [comment]
Somewhat related to your pull request - I expected there to be a release of 1.4 already, since the changelog on master included an entry for that version. I saw later that there is a badge with the latest version in the main readme, but still. 

I see you add a heading for 1.5. 

I think the changelog is easier to use if it only includes actually published changes and not "changes to come" :)

**Comment by eirslett** [comment]
Yes, maybe we should remove the 1.5 part of the changelog. Who knows, maybe a quick hotfix will make it into 1.4 before the release.
I guess we could add the release badge to the changelog as well, and put a sentence there about that being the latest released version.

**Comment by mriehema** [comment]
Hi  @eirslett, hope you had some nice days off. ;-) I changed the files.

**Comment by eirslett** [comment]
Thanks! I'll try to squeeze in some time for a release! :P

**Comment by eirslett** [comment]
Release is rolling out now.

**Pull request merged**
