### PR TITLE
Proxy config now includes (and displays) id

### PR DESCRIPTION
**Pull request by andham**
Signed-off-by: Anders Hammar <anders@hammar.net>

### CODE REVIEW

**Comment by eirslett** [comment]
What is the ID used for?

**Comment by andham** [comment]
The id is...well. an id. :-) It's used to distinguish one proxy def from others. I ran into issue #148 and displaying the id of the proxy used simplifies when you have more than one def.

**Comment by eirslett** [comment]
Sorry for the delay! I'll merge this!

**Comment by eirslett** [comment]
ouch, looks like there is a merge conflict?

**Comment by andham** [comment]
The merge conflict should be fixed now.

**Comment by eirslett** [comment]
Thanks! The build was failing, but I'm sure this change isn't the reason.

**Pull request merged**
