### PR TITLE
Added property to skip the running of "npm install" task, it is time con...

### PR DESCRIPTION
**Pull request by atlipall**
...suming and not always needed

### CODE REVIEW

**Comment by monarchjhaveri** [comment]
Hi, just wanted to know, can we expect the <skip> parameter in a release soon? Can I tell maven to skip a certain <execution> step if the <configuration><skip>....</skip><configuration> parameter is false?

**Comment by eirslett** [comment]
Sorry for being so late! I'll merge this one now.

**Comment by eirslett** [comment]
Thanks for the PR!

**Comment by einarpehrson** [comment]
@eirslett, when can we expect to see this in a release? If you didn't have any plans to create a new release version, I would very much appreciate if you did for this improvement. Thanks!

**Comment by monarchjhaveri** [comment]
Agreed,  please do let us know

**Comment by eirslett** [comment]
@einarpehrson @monarchjhaveri I just released 0.0.21 on Sonatype! Should show up on Maven Central in a couple of hours.

**Comment by monarchjhaveri** [comment]
@eirslett Awesome, thank you so much! Using v0.0.22, works very well and as expected so far :+1:

**Pull request merged**
