### PR TITLE
Allow Bower to use Maven proxy

### PR DESCRIPTION
**Pull request by vldrus**
Using frontend-maven-plugin I found that Bower cannot download files when Maven works via proxy server. So I added to Bower Mojo ability to work via Maven proxy like it is done in NPM Mojo.

### CODE REVIEW

**Comment by Selectorrr** [comment]
@eirslett can you merge this and create new tag?

**Comment by mriehema** [comment]
:+1:

**Comment by antoinebrault** [comment]
any ETA on merge?

**Comment by eirslett** [comment]
Oh sorry, I'll merge it now! Thanks for the PR!

**Comment by vldrus** [comment]
@eirslett, thank you!

**Comment by antoinebrault** [comment]
@eirslett Thanks! Could you release v0.0.27 as well ? :)

**Pull request merged**
