### PR TITLE
prepend node and npm paths to avoid using local node or npm

### PR DESCRIPTION
**Pull request by blackcathacker**
Fixes issue #248. This also allows the installDirectory to be different than the workingDirectory.

### CODE REVIEW

**Comment by robertcsakany** [comment]
I've made very same fix when I see there is an existing pull request. :)

**Comment by Athou** [comment]
Any plan on merging this and releasing it on maven central?

**Comment by eirslett** [comment]
Ok, I'll try to find some time now!

**Comment by xvrl** [comment]
@eirslett same here, would love to see a release to fix this :) thx!

**Comment by tinotruppel** [comment]
same here, getting a release would be awesome, thx!

**Comment by eirslett** [comment]
@Athou @xvrl @tinotruppel Finally I got to release this ;-)

**Pull request merged**
